const STORAGE_KEY = "starplusenergy-asset-index-v1";
const IMPORT_BACKUP_KEY = "starplusenergy-last-import-backup-v1";
const seed = {
  assets: [
    { id: "a1", code: "AST-2024-001", name: "Dell Latitude 7440", category: "Laptop", model: "Latitude 7440", serial: "DL7440-8891", status: "Assigned", location: "Head Office", owner: "Maya Chen", department: "Finance", condition: "Good", notes: "Primary finance laptop", updated: "2024-08-18" },
    { id: "a2", code: "AST-2024-002", name: "HP LaserJet Pro M404", category: "Printer", model: "M404dn", serial: "HP-M404-1142", status: "Available", location: "Head Office", owner: "", department: "", condition: "Good", notes: "Ready for deployment", updated: "2024-08-17" },
    { id: "a3", code: "AST-2024-003", name: "Cisco Catalyst 9200", category: "Network", model: "C9200L-24P", serial: "CS9200-4129", status: "Under repair", location: "IT Store", owner: "", department: "", condition: "Needs service", notes: "Replacement fan ordered", updated: "2024-08-12" },
    { id: "a4", code: "AST-2024-004", name: "MacBook Pro 14-inch", category: "Laptop", model: "M2 Pro", serial: "MBP14-5271", status: "On loan", location: "Regional Office", owner: "Daniel Okoro", department: "Operations", condition: "Excellent", notes: "Due back 30 Aug 2024", updated: "2024-08-10" },
    { id: "a5", code: "AST-2024-005", name: "Epson EB-FH52 Projector", category: "AV Equipment", model: "EB-FH52", serial: "EPFH52-7330", status: "Available", location: "Head Office", owner: "", department: "", condition: "Good", notes: "Meeting room equipment", updated: "2024-08-02" },
    { id: "a6", code: "AST-2024-006", name: "Samsung Galaxy S23", category: "Mobile", model: "SM-S911B", serial: "SGS23-2256", status: "Damaged", location: "Head Office", owner: "Maya Chen", department: "Finance", condition: "Cracked screen", notes: "Awaiting repair assessment", updated: "2024-07-28" }
  ],
  loans: [{ id: "l1", assetCode: "AST-2024-004", borrower: "Daniel Okoro", department: "Operations", loanDate: "2024-08-10", dueDate: "2024-08-30", status: "Active", purpose: "Regional site visit" }],
  employees: [{ name: "Maya Chen", department: "Finance", position: "Finance Lead" }, { name: "Daniel Okoro", department: "Operations", position: "Operations Manager" }, { name: "Priya Shah", department: "IT", position: "Systems Analyst" }],
  departments: ["Finance", "Operations", "IT", "People & Culture"],
  locations: ["Head Office", "Regional Office", "IT Store"]
};
let db = loadDb();
let currentView = "overview";
let searchTerm = "";
let filterStatus = "All statuses";
let searchField = "All fields";
const $ = (selector) => document.querySelector(selector);
function loadDb() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || structuredClone(seed); } catch (error) { return structuredClone(seed); } }
function saveDb() { localStorage.setItem(STORAGE_KEY, JSON.stringify(db)); }
function hasImportBackup() { return Boolean(localStorage.getItem(IMPORT_BACKUP_KEY)); }
function saveImportBackup() { localStorage.setItem(IMPORT_BACKUP_KEY, JSON.stringify(db)); }
function revertLastImport() { const backup = localStorage.getItem(IMPORT_BACKUP_KEY); if (!backup) return toast("No import backup is available"); try { db = JSON.parse(backup); saveDb(); localStorage.removeItem(IMPORT_BACKUP_KEY); render(); toast("Previous database restored"); } catch (error) { toast("The import backup could not be restored"); } }
function esc(value = "") { return String(value).replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char])); }
function toast(message) { const node = $("#toast"); node.textContent = message; node.classList.add("show"); setTimeout(() => node.classList.remove("show"), 2600); }
function statusClass(status) { return status.toLowerCase().replaceAll(" ", "-"); }
function setView(view) { currentView = view; document.querySelectorAll(".nav-item").forEach((button) => button.classList.toggle("active", button.dataset.view === view)); render(); }
function render() { $("#assetNavCount").textContent = db.assets.length; $("#pageTitle").textContent = currentView === "overview" ? "Good morning, James" : ({ assets: "Asset register", loans: "Loans & returns", directory: "People and places", exchange: "Excel exchange" }[currentView]); $("#appView").innerHTML = ({ overview: overviewView, assets: assetsView, loans: loansView, directory: directoryView, exchange: exchangeView }[currentView])(); bindViewEvents(); }
function header(title, copy, action = "") { return `<div class="view-header"><div><h2>${title}</h2><p>${copy}</p></div>${action}</div>`; }
function assetRows(assets) { if (!assets.length) return `<div class="empty">No assets match the current filters.</div>`; return `<div class="table-wrap"><table><thead><tr><th>Asset</th><th>Category</th><th>Status</th><th>Location</th><th>Current holder</th><th></th></tr></thead><tbody>${assets.map((asset) => `<tr><td><div class="asset-name">${esc(asset.name)}</div><div class="asset-code">${esc(asset.code)}</div></td><td>${esc(asset.category)}</td><td><span class="status ${statusClass(asset.status)}">${esc(asset.status)}</span></td><td>${esc(asset.location)}</td><td>${esc(asset.owner || "Unassigned")}</td><td><button class="text-button edit-asset" data-id="${asset.id}">View</button></td></tr>`).join("")}</tbody></table></div>`; }
function overviewView() { const available = db.assets.filter((asset) => asset.status === "Available").length; const assigned = db.assets.filter((asset) => ["Assigned", "On loan"].includes(asset.status)).length; const issues = db.assets.filter((asset) => ["Damaged", "Under repair"].includes(asset.status)).length; const overdue = db.loans.filter((loan) => loan.status === "Overdue").length; const categories = [...new Set(db.assets.map((asset) => asset.category))].map((category) => ({ category, count: db.assets.filter((asset) => asset.category === category).length })).sort((a, b) => b.count - a.count); return `${header("Operations overview", "A live view of your company's asset position.", `<button class="button" id="newAssetButton">+ Add asset</button>`)}<div class="stat-grid"><div class="stat-card"><span class="stat-label">Total assets</span><strong class="stat-value">${db.assets.length}</strong><span class="stat-note">Across ${db.locations.length} locations</span></div><div class="stat-card"><span class="stat-label">Available now</span><strong class="stat-value">${available}</strong><span class="stat-note">Ready to assign</span></div><div class="stat-card warn"><span class="stat-label">On loan / assigned</span><strong class="stat-value">${assigned}</strong><span class="stat-note">Currently with a holder</span></div><div class="stat-card alert"><span class="stat-label">Needs attention</span><strong class="stat-value">${issues + overdue}</strong><span class="stat-note">${issues} asset issues, ${overdue} overdue</span></div></div><div class="content-grid"><section class="panel"><div class="panel-heading"><h3>Recently updated</h3><button class="text-button" data-go="assets">View register →</button></div>${assetRows([...db.assets].sort((a, b) => b.updated.localeCompare(a.updated)).slice(0, 5))}</section><section class="panel"><div class="panel-heading"><h3>Asset mix</h3></div>${categories.map((item) => `<div class="bar-row"><div class="bar-meta"><span>${esc(item.category)}</span><span>${item.count} asset${item.count === 1 ? "" : "s"}</span></div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(12, item.count / db.assets.length * 100)}%"></div></div></div>`).join("")}<div class="panel-heading" style="margin-top:30px"><h3>Quick actions</h3></div><div class="quick-actions"><button id="quickLoan"><span class="quick-icon">↗</span>Record a loan</button><button id="quickImport"><span class="quick-icon">⇄</span>Import Excel</button></div></section></div>`; }
function filteredAssets() { return db.assets.filter((asset) => { const searchable = { "All fields": `${asset.name} ${asset.code} ${asset.category} ${asset.location} ${asset.owner} ${asset.serial}`, "Asset code": asset.code, "Asset name": asset.name, Category: asset.category, Holder: asset.owner, Location: asset.location, "Serial number": asset.serial }[searchField] || ""; return searchable.toLowerCase().includes(searchTerm.toLowerCase()) && (filterStatus === "All statuses" || asset.status === filterStatus); }); }
function updateAssetResults() { const results = filteredAssets(); const count = $("#assetResultCount"); const table = $("#assetResults"); if (count) count.textContent = `${results.length} of ${db.assets.length} assets shown.`; if (table) table.innerHTML = assetRows(results); document.querySelectorAll(".edit-asset").forEach((button) => button.addEventListener("click", () => openAssetModal(button.dataset.id))); }
function assetsView() { const filtered = filteredAssets(); return `${header("Asset register", `<span id="assetResultCount">${filtered.length} of ${db.assets.length} assets shown.</span>`, `<button class="button" id="newAssetButton">+ Add asset</button>`)}<div class="panel"><div class="search-row"><input class="search" id="assetSearch" placeholder="Search asset code (e.g. SPE-1234), name, category or holder" value="${esc(searchTerm)}"><select class="filter" id="searchField"><option>All fields</option><option>Asset code</option><option>Asset name</option><option>Category</option><option>Holder</option><option>Location</option><option>Serial number</option></select><select class="filter" id="statusFilter"><option>All statuses</option>${["Available", "Assigned", "On loan", "Damaged", "Under repair", "Retired"].map((status) => `<option ${filterStatus === status ? "selected" : ""}>${status}</option>`).join("")}</select></div><div id="assetResults">${assetRows(filtered)}</div></div>`; }
function loansView() { return `${header("Loans and returns", "Track internal custody without losing the asset history.", `<button class="button" id="newLoanButton">+ Record loan</button>`)}<section class="panel">${db.loans.length ? `<div class="table-wrap"><table><thead><tr><th>Asset</th><th>Borrower</th><th>Loan date</th><th>Due date</th><th>Status</th><th></th></tr></thead><tbody>${db.loans.map((loan) => { const asset = db.assets.find((item) => item.code === loan.assetCode); return `<tr><td><div class="asset-name">${esc(asset?.name || loan.assetCode)}</div><div class="asset-code">${esc(loan.assetCode)}</div></td><td>${esc(loan.borrower)}<div class="asset-code">${esc(loan.department)}</div></td><td>${esc(loan.loanDate)}</td><td>${esc(loan.dueDate || "No due date")}</td><td><span class="status ${statusClass(loan.status)}">${esc(loan.status)}</span></td><td>${loan.status === "Active" || loan.status === "Overdue" ? `<button class="text-button return-loan" data-id="${loan.id}">Mark returned</button>` : "Returned"}</td></tr>`; }).join("")}</tbody></table></div>` : `<div class="empty">No loan records yet.</div>`}</section>`; }
function directoryView() { return `${header("Directory", "The people, departments, and places behind the asset register.", `<button class="button" id="newAssetButton">+ Add asset</button>`)}<div class="directory-columns"><section class="panel"><h3>Employees</h3><ul class="directory-list">${db.employees.map((person) => `<li><strong>${esc(person.name)}</strong><small>${esc(person.position)} · ${esc(person.department)}</small></li>`).join("")}</ul></section><section class="panel"><h3>Departments</h3><ul class="directory-list">${db.departments.map((item) => `<li>${esc(item)}</li>`).join("")}</ul></section><section class="panel"><h3>Locations</h3><ul class="directory-list">${db.locations.map((item) => `<li>${esc(item)}<small>${db.assets.filter((asset) => asset.location === item).length} assets</small></li>`).join("")}</ul></section></div>`; }
function exchangeView() { return `${header("Excel exchange", "Import and export the SPE IT equipment loan list format.") }<div class="exchange-grid"><section class="exchange-card"><h3>Export loan list</h3><p>Download the current loans in the same XLSX structure as SPE_IT_Equipment_Loan_List_Example.xlsx.</p><button class="button" id="exportButton">↓ Export XLSX loan list</button></section><section class="exchange-card"><h3>Replace database from Excel</h3><p>Import the reference workbook as the complete database. Asset numbers such as SPE-1234 come from the Laptop column. Existing data is replaced after a local restore point is saved.</p><div class="drop-zone">Choose a local XLSX file<input type="file" id="importFile" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"></div></section></div><div class="notice"><strong>Offline data note:</strong> The workbook parser and writer are bundled in this application. No CDN, internet, or online spreadsheet service is required.</div><div class="panel import-backup-panel"><div><strong>Restore point</strong><p>${hasImportBackup() ? "A backup of the database before the last import is available." : "No import restore point is currently available."}</p></div><button class="button ${hasImportBackup() ? "secondary" : "ghost"}" id="revertImportButton" ${hasImportBackup() ? "" : "disabled"}>↶ Revert last import</button></div>`; }
function bindViewEvents() { $("#newAssetButton")?.addEventListener("click", () => openAssetModal()); $("#newLoanButton")?.addEventListener("click", () => openLoanModal()); $("#quickLoan")?.addEventListener("click", () => openLoanModal()); $("#quickImport")?.addEventListener("click", () => setView("exchange")); $("#exportButton")?.addEventListener("click", exportWorkbook); $("#importFile")?.addEventListener("change", importWorkbook); $("#revertImportButton")?.addEventListener("click", revertLastImport); $("#assetSearch")?.addEventListener("input", (event) => { searchTerm = event.target.value; updateAssetResults(); }); $("#searchField")?.addEventListener("change", (event) => { searchField = event.target.value; updateAssetResults(); }); $("#statusFilter")?.addEventListener("change", (event) => { filterStatus = event.target.value; updateAssetResults(); }); document.querySelectorAll(".edit-asset").forEach((button) => button.addEventListener("click", () => openAssetModal(button.dataset.id))); document.querySelectorAll(".return-loan").forEach((button) => button.addEventListener("click", () => returnLoan(button.dataset.id))); document.querySelectorAll("[data-go]").forEach((button) => button.addEventListener("click", () => setView(button.dataset.go))); }
function inputField(label, name, value = "", full = false, type = "text") { return `<div class="field ${full ? "full" : ""}"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${esc(value)}" ${name === "code" ? "required" : ""}></div>`; }
function openModal(html) { $("#modalContent").innerHTML = html; $("#modalBackdrop").classList.remove("hidden"); }
function closeModal() { $("#modalBackdrop").classList.add("hidden"); }
function openAssetModal(id = "") { const asset = db.assets.find((item) => item.id === id) || { code: `AST-${new Date().getFullYear()}-${String(db.assets.length + 1).padStart(3, "0")}`, name: "", category: "Laptop", model: "", serial: "", status: "Available", location: db.locations[0], owner: "", department: "", condition: "Good", notes: "" }; openModal(`<h2 id="modalTitle">${id ? "Asset details" : "Add asset"}</h2><p class="modal-intro">The asset remains the master record through every assignment and return.</p><form id="assetForm"><div class="form-grid">${inputField("Asset code", "code", asset.code)}${inputField("Asset name", "name", asset.name)}${inputField("Category", "category", asset.category)}${inputField("Model", "model", asset.model)}${inputField("Serial number", "serial", asset.serial)}<div class="field"><label for="status">Status</label><select id="status" name="status">${["Available", "Assigned", "On loan", "Damaged", "Under repair", "Retired"].map((status) => `<option ${asset.status === status ? "selected" : ""}>${status}</option>`).join("")}</select></div><div class="field"><label for="location">Location</label><select id="location" name="location">${db.locations.map((place) => `<option ${asset.location === place ? "selected" : ""}>${esc(place)}</option>`).join("")}</select></div>${inputField("Current holder", "owner", asset.owner)}${inputField("Department", "department", asset.department)}${inputField("Condition", "condition", asset.condition)}${inputField("Notes", "notes", asset.notes, true)}</div><div class="form-actions"><button type="button" class="button ghost" id="cancelModal">Cancel</button><button class="button">${id ? "Save changes" : "Create asset"}</button></div></form>`); $("#cancelModal").addEventListener("click", closeModal); $("#assetForm").addEventListener("submit", (event) => { event.preventDefault(); const form = new FormData(event.target); const values = Object.fromEntries(form.entries()); if (!values.code || !values.name) return; const now = new Date().toISOString().slice(0, 10); if (id) Object.assign(asset, values, { updated: now }); else db.assets.unshift({ id: crypto.randomUUID(), ...values, updated: now }); saveDb(); closeModal(); render(); toast(id ? "Asset updated" : "Asset added to the register"); }); }
function openLoanModal() { const available = db.assets.filter((asset) => asset.status === "Available"); openModal(`<h2 id="modalTitle">Record internal loan</h2><p class="modal-intro">This creates a custody record and changes the selected asset status to On loan.</p><form id="loanForm"><div class="form-grid"><div class="field full"><label for="assetCode">Asset</label><select id="assetCode" name="assetCode" required>${available.map((asset) => `<option value="${esc(asset.code)}">${esc(asset.code)} — ${esc(asset.name)}</option>`).join("")}</select></div><div class="field"><label for="borrower">Borrower</label><select id="borrower" name="borrower" required>${db.employees.map((person) => `<option>${esc(person.name)}</option>`).join("")}</select></div>${inputField("Department", "department", "Operations")}${inputField("Loan date", "loanDate", new Date().toISOString().slice(0, 10), false, "date")}${inputField("Due date (optional)", "dueDate", "", false, "date")}${inputField("Purpose", "purpose", "", true)}</div><div class="form-actions"><button type="button" class="button ghost" id="cancelModal">Cancel</button><button class="button" ${available.length ? "" : "disabled"}>Create loan</button></div></form>`); $("#cancelModal").addEventListener("click", closeModal); $("#loanForm").addEventListener("submit", (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.target).entries()); const asset = db.assets.find((item) => item.code === values.assetCode); if (!asset) return; asset.status = "On loan"; asset.owner = values.borrower; asset.department = values.department; asset.updated = values.loanDate; db.loans.unshift({ id: crypto.randomUUID(), ...values, status: "Active" }); saveDb(); closeModal(); setView("loans"); toast("Loan recorded"); }); }
function returnLoan(id) { const loan = db.loans.find((item) => item.id === id); if (!loan) return; loan.status = "Returned"; loan.returnedDate = new Date().toISOString().slice(0, 10); const asset = db.assets.find((item) => item.code === loan.assetCode); if (asset) { asset.status = "Available"; asset.owner = ""; asset.department = ""; asset.updated = loan.returnedDate; } saveDb(); render(); toast("Asset returned and available"); }
const loanHeaders = ["no", "Name", "Knox ID", "Rental Location", "IP", "Start Date", "Pickup Date", "End Date", "Return Date", "Laptop", "Charging _x000D_\nAdapter", "Charging _x000D_\nCable", "Dongle", "Keyboard", "Mouse", "Monitor", "Ethernet cable", "others", "Note"];
function loanRows() { return db.loans.map((loan, index) => { const asset = db.assets.find((item) => item.code === loan.assetCode) || {}; const equipment = loan.equipment || {}; return [index + 1, loan.borrower || "", loan.knoxId || "", asset.location || loan.location || "", loan.ip || "", loan.startDate || loan.loanDate || "", loan.pickupDate || loan.loanDate || "", loan.endDate || loan.dueDate || "", loan.returnDate || loan.returnedDate || "", loan.assetCode || "", equipment.Adapter ?? 1, equipment.Cable ?? 1, equipment.Dongle ?? 0, equipment.Keyboard ?? 0, equipment.Mouse ?? 0, equipment.Monitor ?? 0, equipment["Ethernet cable"] ?? 0, loan.others || "", loan.note || loan.purpose || ""]; }); }
async function exportWorkbook() { const rows = [loanHeaders, ...loanRows()]; const workbook = await makeXlsx(rows); download(new Blob([workbook], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }), `SPE_IT_Equipment_Loan_List_${new Date().toISOString().slice(0, 10)}.xlsx`); toast("Reference-format .xlsx workbook downloaded"); }
function download(blob, filename) { const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = filename; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); }
function parseDelimited(text) { const lines = text.replace(/^\uFEFF/, "").trim().split(/\r?\n/).filter(Boolean); if (!lines.length) return []; const delimiter = lines[0].includes("\t") ? "\t" : ","; return lines.map((line) => { const cells = []; let cell = "", quote = false; for (const char of line) { if (char === '"') quote = !quote; else if (char === delimiter && !quote) { cells.push(cell.trim()); cell = ""; } else cell += char; } cells.push(cell.trim().replace(/^"|"$/g, "")); return cells; }); }
async function importWorkbook(event) { const file = event.target.files[0]; if (!file) return; try { const rows = await readXlsx(file); if (rows.length < 2) throw new Error("The workbook has no loan rows"); const headers = rows[0].map((header) => String(header).trim().toLowerCase()); const column = (name) => headers.indexOf(name.toLowerCase()); const assetCodeIndex = column("laptop"), borrowerIndex = column("name"); if (assetCodeIndex < 0 || borrowerIndex < 0) throw new Error("This is not the SPE loan-list format: Laptop and Name are required"); const importedAssets = [], importedLoans = [], importedEmployees = [], importedLocations = new Set(); let rejected = 0; rows.slice(1).forEach((row) => { const code = String(row[assetCodeIndex] || "").trim(), borrower = String(row[borrowerIndex] || "").trim(); if (!code || !borrower) { rejected++; return; } const value = (name) => row[column(name)] || ""; const location = String(value("rental location")); const returned = String(value("return date")); importedLocations.add(location || "Unspecified"); importedEmployees.push({ name: borrower, department: "", position: "" }); importedAssets.push({ id: crypto.randomUUID(), code, name: "Laptop", category: "Laptop", model: "", serial: "", status: returned ? "Assigned" : "On loan", location: location || "Unspecified", owner: borrower, department: "", condition: "Good", notes: String(value("note")), updated: new Date().toISOString().slice(0, 10) }); importedLoans.push({ id: crypto.randomUUID(), assetCode: code, knoxId: String(value("knox id")), borrower, location, ip: String(value("ip")), startDate: String(value("start date")), pickupDate: String(value("pickup date")), endDate: String(value("end date")), returnDate: returned, loanDate: String(value("start date")), dueDate: String(value("end date")), returnedDate: returned, status: returned ? "Returned" : "Active", equipment: { Adapter: value("charging _x000d_\nadapter"), Cable: value("charging _x000d_\ncable"), Dongle: value("dongle"), Keyboard: value("keyboard"), Mouse: value("mouse"), Monitor: value("monitor"), "Ethernet cable": value("ethernet cable") }, others: String(value("others")), note: String(value("note")) }); }); if (!importedLoans.length) throw new Error("The workbook contains no valid loan rows"); saveImportBackup(); db = { assets: importedAssets, loans: importedLoans, employees: importedEmployees.filter((person, index, people) => people.findIndex((item) => item.name === person.name) === index), departments: [], locations: [...importedLocations] }; saveDb(); render(); toast(`Import replaced database: ${importedAssets.length} assets, ${importedLoans.length} loans, ${rejected} rejected`); } catch (error) { toast(error.message); } event.target.value = ""; }
function xmlEscape(value) { return esc(String(value ?? "")); }
function columnName(number) { let name = ""; while (number) { const remainder = (number - 1) % 26; name = String.fromCharCode(65 + remainder) + name; number = Math.floor((number - 1) / 26); } return name; }
function columnNumber(name) { return [...name].reduce((total, character) => total * 26 + character.charCodeAt(0) - 64, 0); }
function crc32(bytes) { let crc = 0xffffffff; for (const byte of bytes) { crc ^= byte; for (let bit = 0; bit < 8; bit++) crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1)); } return (crc ^ 0xffffffff) >>> 0; }
function concatBytes(chunks) { const result = new Uint8Array(chunks.reduce((size, chunk) => size + chunk.length, 0)); let offset = 0; chunks.forEach((chunk) => { result.set(chunk, offset); offset += chunk.length; }); return result; }
function zipStore(files) { const encoder = new TextEncoder(), chunks = [], central = [], now = new Uint8Array([0, 0, 0, 0]); let offset = 0; files.forEach(([name, content]) => { const nameBytes = encoder.encode(name), data = encoder.encode(content), crc = crc32(data); const header = new ArrayBuffer(30 + nameBytes.length), view = new DataView(header); view.setUint32(0, 0x04034b50, true); view.setUint16(4, 20, true); view.setUint16(6, 0, true); view.setUint16(8, 0, true); view.setUint32(14, crc, true); view.setUint32(18, data.length, true); view.setUint32(22, data.length, true); view.setUint16(26, nameBytes.length, true); new Uint8Array(header, 30).set(nameBytes); chunks.push(new Uint8Array(header), data); const directory = new ArrayBuffer(46 + nameBytes.length), dir = new DataView(directory); dir.setUint32(0, 0x02014b50, true); dir.setUint16(4, 20, true); dir.setUint16(6, 20, true); dir.setUint16(8, 0, true); dir.setUint16(10, 0, true); dir.setUint32(16, crc, true); dir.setUint32(20, data.length, true); dir.setUint32(24, data.length, true); dir.setUint16(28, nameBytes.length, true); dir.setUint32(42, offset, true); new Uint8Array(directory, 46).set(nameBytes); central.push(new Uint8Array(directory)); offset += header.byteLength + data.length; }); const centralBytes = concatBytes(central), end = new ArrayBuffer(22), endView = new DataView(end); endView.setUint32(0, 0x06054b50, true); endView.setUint16(8, files.length, true); endView.setUint16(10, files.length, true); endView.setUint32(12, centralBytes.length, true); endView.setUint32(16, offset, true); return concatBytes([...chunks, centralBytes, new Uint8Array(end)]).buffer; }
async function makeXlsx(rows) { const shared = [], sharedIndex = new Map(); const sharedValue = (value) => { const text = String(value ?? ""); if (!sharedIndex.has(text)) { sharedIndex.set(text, shared.length); shared.push(text); } return sharedIndex.get(text); }; const sheetRows = rows.map((row, rowIndex) => `<row r="${rowIndex + 1}">${row.map((value, columnIndex) => { const cell = `${columnName(columnIndex + 1)}${rowIndex + 1}`; return `<c r="${cell}" t="s"><v>${sharedValue(value)}</v></c>`; }).join("")}</row>`).join(""); const sheet = `<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1:S${rows.length}"/><sheetData>${sheetRows}</sheetData></worksheet>`; const strings = `<?xml version="1.0" encoding="UTF-8"?><sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="${shared.length}" uniqueCount="${shared.length}">${shared.map((value) => `<si><t>${xmlEscape(value)}</t></si>`).join("")}</sst>`; const workbook = `<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Sheet1" sheetId="1" r:id="rId1"/></sheets></workbook>`; const rels = `<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml"/></Relationships>`; const rootRels = `<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`; const types = `<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/sharedStrings.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"/></Types>`; return zipStore([["[Content_Types].xml", types], ["_rels/.rels", rootRels], ["xl/workbook.xml", workbook], ["xl/_rels/workbook.xml.rels", rels], ["xl/worksheets/sheet1.xml", sheet], ["xl/sharedStrings.xml", strings]]); }
async function readXlsx(file) { const bytes = new Uint8Array(await file.arrayBuffer()), decoder = new TextDecoder(), files = {}; let offset = 0; while (offset + 30 < bytes.length) { const view = new DataView(bytes.buffer, bytes.byteOffset + offset); if (view.getUint32(0, true) !== 0x04034b50) { offset++; continue; } const method = view.getUint16(8, true), compressedSize = view.getUint32(18, true), nameSize = view.getUint16(26, true), extraSize = view.getUint16(28, true), name = decoder.decode(bytes.slice(offset + 30, offset + 30 + nameSize)), start = offset + 30 + nameSize + extraSize, compressed = bytes.slice(start, start + compressedSize); let data = compressed; if (method === 8) { const stream = new DecompressionStream("deflate-raw"); data = new Uint8Array(await new Response(new Blob([compressed]).stream().pipeThrough(stream)).arrayBuffer()); } files[name] = decoder.decode(data); offset = start + compressedSize; } const strings = [...(files["xl/sharedStrings.xml"] || "").matchAll(/<si>[\s\S]*?<t[^>]*>([\s\S]*?)<\/t>[\s\S]*?<\/si>/g)].map((match) => new DOMParser().parseFromString(`<t>${match[1]}</t>`, "text/xml").documentElement.textContent); const sheet = files["xl/worksheets/sheet1.xml"] || ""; return [...sheet.matchAll(/<row[^>]*>([\s\S]*?)<\/row>/g)].map((rowMatch) => { const row = []; [...rowMatch[1].matchAll(/<c([^>]*)>\s*<v>([\s\S]*?)<\/v>\s*<\/c>/g)].forEach((cell) => { const reference = cell[1].match(/\br="([A-Z]+)\d+"/), type = cell[1].match(/\bt="([^"]+)"/), value = type?.[1] === "s" ? strings[Number(cell[2])] || "" : cell[2]; if (reference) row[columnNumber(reference[1]) - 1] = value; }); return row; }); }
$("#modalClose").addEventListener("click", closeModal); $("#modalBackdrop").addEventListener("click", (event) => { if (event.target === $("#modalBackdrop")) closeModal(); }); document.querySelectorAll(".nav-item").forEach((button) => button.addEventListener("click", () => setView(button.dataset.view))); $("#todayLabel").textContent = new Intl.DateTimeFormat("en", { weekday: "long", month: "long", day: "numeric" }).format(new Date()).toUpperCase(); render();
