const STORAGE_KEY = "starplusenergy-asset-index-v1";
const seed = {
  assets: [
    { id: "a1", code: "AST-2024-001", name: "Dell Latitude 7440", category: "Laptop", model: "Latitude 7440", serial: "DL7440-8891", status: "Assigned", location: "Head Office", owner: "Maya Chen", department: "Finance", condition: "Good", notes: "Primary finance laptop", updated: "2024-08-18" },
    { id: "a2", code: "AST-2024-002", name: "HP LaserJet Pro M404", category: "Printer", model: "M404dn", serial: "HP-M404-1142", status: "Available", location: "Head Office", owner: "", department: "", condition: "Good", notes: "Ready for deployment", updated: "2024-08-17" },
    { id: "a3", code: "AST-2024-003", name: "Cisco Catalyst 9200", category: "Network", model: "C9200L-24P", serial: "CS9200-4129", status: "Under repair", location: "IT Store", owner: "", department: "", condition: "Needs service", notes: "Replacement fan ordered", updated: "2024-08-12" },
    { id: "a4", code: "AST-2024-004", name: "MacBook Pro 14-inch", category: "Laptop", model: "M2 Pro", serial: "MBP14-5271", status: "On loan", location: "Regional Office", owner: "Daniel Okoro", department: "Operations", condition: "Excellent", notes: "Due back 30 Aug 2024", updated: "2024-08-10" },
    { id: "a5", code: "AST-2024-005", name: "Epson EB-FH52 Projector", category: "AV Equipment", model: "EB-FH52", serial: "EPFH52-7330", status: "Available", location: "Head Office", owner: "", department: "", condition: "Good", notes: "Meeting room equipment", updated: "2024-08-02" },
    { id: "a6", code: "AST-2024-006", name: "Samsung Galaxy S23", category: "Mobile", model: "SM-S911B", serial: "SGS23-2256", status: "Damaged", location: "Head Office", owner: "Maya Chen", department: "Finance", condition: "Cracked screen", notes: "Awaiting repair assessment", updated: "2024-07-28" }
  ],
  loans: [{ id: "l1", assetCode: "AST-2024-004", borrower: "Daniel Okoro", department: "Operations", loanDate: "2024-08-10", dueDate: "2024-08-30", status: "Active", purpose: "Regional site visit" }],
  employees: [{ name: "Maya Chen", department: "Finance", position: "Finance Lead" }, { name: "Daniel Okoro", department: "Operations", position: "Operations Manager" }, { name: "Priya Shah", department: "IT", position: "Systems Analyst" }],
  departments: ["Finance", "Operations", "IT", "People & Culture"],
  locations: ["Head Office", "Regional Office", "IT Store"]
};
let db = loadDb();
let currentView = "overview";
let searchTerm = "";
let filterStatus = "All statuses";
let searchField = "All fields";
const $ = (selector) => document.querySelector(selector);
function loadDb() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || structuredClone(seed); } catch (error) { return structuredClone(seed); } }
function saveDb() { localStorage.setItem(STORAGE_KEY, JSON.stringify(db)); }
function esc(value = "") { return String(value).replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char])); }
function toast(message) { const node = $("#toast"); node.textContent = message; node.classList.add("show"); setTimeout(() => node.classList.remove("show"), 2600); }
function statusClass(status) { return status.toLowerCase().replaceAll(" ", "-"); }
function setView(view) { currentView = view; document.querySelectorAll(".nav-item").forEach((button) => button.classList.toggle("active", button.dataset.view === view)); render(); }
function render() { $("#assetNavCount").textContent = db.assets.length; $("#pageTitle").textContent = currentView === "overview" ? "Good morning, James" : ({ assets: "Asset register", loans: "Loans & returns", directory: "People and places", exchange: "Excel exchange" }[currentView]); $("#appView").innerHTML = ({ overview: overviewView, assets: assetsView, loans: loansView, directory: directoryView, exchange: exchangeView }[currentView])(); bindViewEvents(); }
function header(title, copy, action = "") { return `<div class="view-header"><div><h2>${title}</h2><p>${copy}</p></div>${action}</div>`; }
function assetRows(assets) { if (!assets.length) return `<div class="empty">No assets match the current filters.</div>`; return `<div class="table-wrap"><table><thead><tr><th>Asset</th><th>Category</th><th>Status</th><th>Location</th><th>Current holder</th><th></th></tr></thead><tbody>${assets.map((asset) => `<tr><td><div class="asset-name">${esc(asset.name)}</div><div class="asset-code">${esc(asset.code)}</div></td><td>${esc(asset.category)}</td><td><span class="status ${statusClass(asset.status)}">${esc(asset.status)}</span></td><td>${esc(asset.location)}</td><td>${esc(asset.owner || "Unassigned")}</td><td><button class="text-button edit-asset" data-id="${asset.id}">View</button></td></tr>`).join("")}</tbody></table></div>`; }
function overviewView() { const available = db.assets.filter((asset) => asset.status === "Available").length; const assigned = db.assets.filter((asset) => ["Assigned", "On loan"].includes(asset.status)).length; const issues = db.assets.filter((asset) => ["Damaged", "Under repair"].includes(asset.status)).length; const overdue = db.loans.filter((loan) => loan.status === "Overdue").length; const categories = [...new Set(db.assets.map((asset) => asset.category))].map((category) => ({ category, count: db.assets.filter((asset) => asset.category === category).length })).sort((a, b) => b.count - a.count); return `${header("Operations overview", "A live view of your company's asset position.", `<button class="button" id="newAssetButton">+ Add asset</button>`)}<div class="stat-grid"><div class="stat-card"><span class="stat-label">Total assets</span><strong class="stat-value">${db.assets.length}</strong><span class="stat-note">Across ${db.locations.length} locations</span></div><div class="stat-card"><span class="stat-label">Available now</span><strong class="stat-value">${available}</strong><span class="stat-note">Ready to assign</span></div><div class="stat-card warn"><span class="stat-label">On loan / assigned</span><strong class="stat-value">${assigned}</strong><span class="stat-note">Currently with a holder</span></div><div class="stat-card alert"><span class="stat-label">Needs attention</span><strong class="stat-value">${issues + overdue}</strong><span class="stat-note">${issues} asset issues, ${overdue} overdue</span></div></div><div class="content-grid"><section class="panel"><div class="panel-heading"><h3>Recently updated</h3><button class="text-button" data-go="assets">View register →</button></div>${assetRows([...db.assets].sort((a, b) => b.updated.localeCompare(a.updated)).slice(0, 5))}</section><section class="panel"><div class="panel-heading"><h3>Asset mix</h3></div>${categories.map((item) => `<div class="bar-row"><div class="bar-meta"><span>${esc(item.category)}</span><span>${item.count} asset${item.count === 1 ? "" : "s"}</span></div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(12, item.count / db.assets.length * 100)}%"></div></div></div>`).join("")}<div class="panel-heading" style="margin-top:30px"><h3>Quick actions</h3></div><div class="quick-actions"><button id="quickLoan"><span class="quick-icon">↗</span>Record a loan</button><button id="quickImport"><span class="quick-icon">⇄</span>Import Excel</button></div></section></div>`; }
function filteredAssets() { return db.assets.filter((asset) => { const searchable = { "All fields": `${asset.name} ${asset.code} ${asset.category} ${asset.location} ${asset.owner} ${asset.serial}`, "Asset code": asset.code, "Asset name": asset.name, Category: asset.category, Holder: asset.owner, Location: asset.location, "Serial number": asset.serial }[searchField] || ""; return searchable.toLowerCase().includes(searchTerm.toLowerCase()) && (filterStatus === "All statuses" || asset.status === filterStatus); }); }
function updateAssetResults() { const results = filteredAssets(); const count = $("#assetResultCount"); const table = $("#assetResults"); if (count) count.textContent = `${results.length} of ${db.assets.length} assets shown.`; if (table) table.innerHTML = assetRows(results); document.querySelectorAll(".edit-asset").forEach((button) => button.addEventListener("click", () => openAssetModal(button.dataset.id))); }
function assetsView() { const filtered = filteredAssets(); return `${header("Asset register", `<span id="assetResultCount">${filtered.length} of ${db.assets.length} assets shown.</span>`, `<button class="button" id="newAssetButton">+ Add asset</button>`)}<div class="panel"><div class="search-row"><input class="search" id="assetSearch" placeholder="Search asset code (e.g. SPE-1234), name, category or holder" value="${esc(searchTerm)}"><select class="filter" id="searchField"><option>All fields</option><option>Asset code</option><option>Asset name</option><option>Category</option><option>Holder</option><option>Location</option><option>Serial number</option></select><select class="filter" id="statusFilter"><option>All statuses</option>${["Available", "Assigned", "On loan", "Damaged", "Under repair", "Retired"].map((status) => `<option ${filterStatus === status ? "selected" : ""}>${status}</option>`).join("")}</select></div><div id="assetResults">${assetRows(filtered)}</div></div>`; }
function loansView() { return `${header("Loans and returns", "Track internal custody without losing the asset history.", `<button class="button" id="newLoanButton">+ Record loan</button>`)}<section class="panel">${db.loans.length ? `<div class="table-wrap"><table><thead><tr><th>Asset</th><th>Borrower</th><th>Loan date</th><th>Due date</th><th>Status</th><th></th></tr></thead><tbody>${db.loans.map((loan) => { const asset = db.assets.find((item) => item.code === loan.assetCode); return `<tr><td><div class="asset-name">${esc(asset?.name || loan.assetCode)}</div><div class="asset-code">${esc(loan.assetCode)}</div></td><td>${esc(loan.borrower)}<div class="asset-code">${esc(loan.department)}</div></td><td>${esc(loan.loanDate)}</td><td>${esc(loan.dueDate || "No due date")}</td><td><span class="status ${statusClass(loan.status)}">${esc(loan.status)}</span></td><td>${loan.status === "Active" || loan.status === "Overdue" ? `<button class="text-button return-loan" data-id="${loan.id}">Mark returned</button>` : "Returned"}</td></tr>`; }).join("")}</tbody></table></div>` : `<div class="empty">No loan records yet.</div>`}</section>`; }
function directoryView() { return `${header("Directory", "The people, departments, and places behind the asset register.", `<button class="button" id="newAssetButton">+ Add asset</button>`)}<div class="directory-columns"><section class="panel"><h3>Employees</h3><ul class="directory-list">${db.employees.map((person) => `<li><strong>${esc(person.name)}</strong><small>${esc(person.position)} · ${esc(person.department)}</small></li>`).join("")}</ul></section><section class="panel"><h3>Departments</h3><ul class="directory-list">${db.departments.map((item) => `<li>${esc(item)}</li>`).join("")}</ul></section><section class="panel"><h3>Locations</h3><ul class="directory-list">${db.locations.map((item) => `<li>${esc(item)}<small>${db.assets.filter((asset) => asset.location === item).length} assets</small></li>`).join("")}</ul></section></div>`; }
function exchangeView() { return `${header("Excel exchange", "Move data in and out of this offline workspace using Excel-compatible files.") }<div class="exchange-grid"><section class="exchange-card"><h3>Export register</h3><p>Download the current asset register as an Excel-compatible workbook. Filters from the register view are respected.</p><button class="button" id="exportButton">↓ Export .xls workbook</button></section><section class="exchange-card"><h3>Import assets</h3><p>Upload a CSV, tab-separated file, or Excel-compatible HTML workbook. Existing assets are updated by asset code.</p><div class="drop-zone">Choose a local file<input type="file" id="importFile" accept=".csv,.tsv,.txt,.xls,text/csv,text/plain"></div></section></div><div class="notice"><strong>Offline data note:</strong> This application has no network dependency. Data is stored in this browser on this device. Use the backup button in the top bar before moving to another workstation.</div>`; }
function bindViewEvents() { $("#newAssetButton")?.addEventListener("click", () => openAssetModal()); $("#newLoanButton")?.addEventListener("click", () => openLoanModal()); $("#quickLoan")?.addEventListener("click", () => openLoanModal()); $("#quickImport")?.addEventListener("click", () => setView("exchange")); $("#exportButton")?.addEventListener("click", exportWorkbook); $("#importFile")?.addEventListener("change", importWorkbook); $("#assetSearch")?.addEventListener("input", (event) => { searchTerm = event.target.value; updateAssetResults(); }); $("#searchField")?.addEventListener("change", (event) => { searchField = event.target.value; updateAssetResults(); }); $("#statusFilter")?.addEventListener("change", (event) => { filterStatus = event.target.value; updateAssetResults(); }); document.querySelectorAll(".edit-asset").forEach((button) => button.addEventListener("click", () => openAssetModal(button.dataset.id))); document.querySelectorAll(".return-loan").forEach((button) => button.addEventListener("click", () => returnLoan(button.dataset.id))); document.querySelectorAll("[data-go]").forEach((button) => button.addEventListener("click", () => setView(button.dataset.go))); }
function inputField(label, name, value = "", full = false, type = "text") { return `<div class="field ${full ? "full" : ""}"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${esc(value)}" ${name === "code" ? "required" : ""}></div>`; }
function openModal(html) { $("#modalContent").innerHTML = html; $("#modalBackdrop").classList.remove("hidden"); }
function closeModal() { $("#modalBackdrop").classList.add("hidden"); }
function openAssetModal(id = "") { const asset = db.assets.find((item) => item.id === id) || { code: `AST-${new Date().getFullYear()}-${String(db.assets.length + 1).padStart(3, "0")}`, name: "", category: "Laptop", model: "", serial: "", status: "Available", location: db.locations[0], owner: "", department: "", condition: "Good", notes: "" }; openModal(`<h2 id="modalTitle">${id ? "Asset details" : "Add asset"}</h2><p class="modal-intro">The asset remains the master record through every assignment and return.</p><form id="assetForm"><div class="form-grid">${inputField("Asset code", "code", asset.code)}${inputField("Asset name", "name", asset.name)}${inputField("Category", "category", asset.category)}${inputField("Model", "model", asset.model)}${inputField("Serial number", "serial", asset.serial)}<div class="field"><label for="status">Status</label><select id="status" name="status">${["Available", "Assigned", "On loan", "Damaged", "Under repair", "Retired"].map((status) => `<option ${asset.status === status ? "selected" : ""}>${status}</option>`).join("")}</select></div><div class="field"><label for="location">Location</label><select id="location" name="location">${db.locations.map((place) => `<option ${asset.location === place ? "selected" : ""}>${esc(place)}</option>`).join("")}</select></div>${inputField("Current holder", "owner", asset.owner)}${inputField("Department", "department", asset.department)}${inputField("Condition", "condition", asset.condition)}${inputField("Notes", "notes", asset.notes, true)}</div><div class="form-actions"><button type="button" class="button ghost" id="cancelModal">Cancel</button><button class="button">${id ? "Save changes" : "Create asset"}</button></div></form>`); $("#cancelModal").addEventListener("click", closeModal); $("#assetForm").addEventListener("submit", (event) => { event.preventDefault(); const form = new FormData(event.target); const values = Object.fromEntries(form.entries()); if (!values.code || !values.name) return; const now = new Date().toISOString().slice(0, 10); if (id) Object.assign(asset, values, { updated: now }); else db.assets.unshift({ id: crypto.randomUUID(), ...values, updated: now }); saveDb(); closeModal(); render(); toast(id ? "Asset updated" : "Asset added to the register"); }); }
function openLoanModal() { const available = db.assets.filter((asset) => asset.status === "Available"); openModal(`<h2 id="modalTitle">Record internal loan</h2><p class="modal-intro">This creates a custody record and changes the selected asset status to On loan.</p><form id="loanForm"><div class="form-grid"><div class="field full"><label for="assetCode">Asset</label><select id="assetCode" name="assetCode" required>${available.map((asset) => `<option value="${esc(asset.code)}">${esc(asset.code)} — ${esc(asset.name)}</option>`).join("")}</select></div><div class="field"><label for="borrower">Borrower</label><select id="borrower" name="borrower" required>${db.employees.map((person) => `<option>${esc(person.name)}</option>`).join("")}</select></div>${inputField("Department", "department", "Operations")}${inputField("Loan date", "loanDate", new Date().toISOString().slice(0, 10), false, "date")}${inputField("Due date (optional)", "dueDate", "", false, "date")}${inputField("Purpose", "purpose", "", true)}</div><div class="form-actions"><button type="button" class="button ghost" id="cancelModal">Cancel</button><button class="button" ${available.length ? "" : "disabled"}>Create loan</button></div></form>`); $("#cancelModal").addEventListener("click", closeModal); $("#loanForm").addEventListener("submit", (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.target).entries()); const asset = db.assets.find((item) => item.code === values.assetCode); if (!asset) return; asset.status = "On loan"; asset.owner = values.borrower; asset.department = values.department; asset.updated = values.loanDate; db.loans.unshift({ id: crypto.randomUUID(), ...values, status: "Active" }); saveDb(); closeModal(); setView("loans"); toast("Loan recorded"); }); }
function returnLoan(id) { const loan = db.loans.find((item) => item.id === id); if (!loan) return; loan.status = "Returned"; loan.returnedDate = new Date().toISOString().slice(0, 10); const asset = db.assets.find((item) => item.code === loan.assetCode); if (asset) { asset.status = "Available"; asset.owner = ""; asset.department = ""; asset.updated = loan.returnedDate; } saveDb(); render(); toast("Asset returned and available"); }
function exportWorkbook() { const rows = db.assets.map((asset) => [asset.code, asset.name, asset.category, asset.model, asset.serial, asset.status, asset.location, asset.owner, asset.department, asset.condition, asset.notes, asset.updated]); const headers = ["Asset Code", "Asset Name", "Category", "Model", "Serial Number", "Status", "Location", "Current Holder", "Department", "Condition", "Notes", "Last Updated"]; const table = `<html><head><meta charset="UTF-8"></head><body><table><tr>${headers.map((header) => `<th>${esc(header)}</th>`).join("")}</tr>${rows.map((row) => `<tr>${row.map((cell) => `<td>${esc(cell)}</td>`).join("")}</tr>`).join("")}</table></body></html>`; download(new Blob([table], { type: "application/vnd.ms-excel" }), `asset-register-${new Date().toISOString().slice(0, 10)}.xls`); toast("Excel-compatible workbook downloaded"); }
function download(blob, filename) { const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = filename; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); }
function parseDelimited(text) { const lines = text.replace(/^\uFEFF/, "").trim().split(/\r?\n/).filter(Boolean); if (!lines.length) return []; const delimiter = lines[0].includes("\t") ? "\t" : ","; return lines.map((line) => { const cells = []; let cell = "", quote = false; for (const char of line) { if (char === '"') quote = !quote; else if (char === delimiter && !quote) { cells.push(cell.trim()); cell = ""; } else cell += char; } cells.push(cell.trim().replace(/^"|"$/g, "")); return cells; }); }
function importWorkbook(event) { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { const rows = parseDelimited(reader.result); if (rows.length < 2) return toast("The file has no importable rows"); const headers = rows[0].map((header) => header.toLowerCase().replace(/[^a-z0-9]/g, "")); const index = (names) => names.map((name) => headers.indexOf(name)).find((position) => position >= 0); const codeIndex = index(["assetcode", "code"]), nameIndex = index(["assetname", "name"]); if (codeIndex === undefined || nameIndex === undefined) return toast("Import needs Asset Code and Asset Name columns"); let added = 0, updated = 0, rejected = 0; rows.slice(1).forEach((row) => { const code = row[codeIndex]?.trim(), name = row[nameIndex]?.trim(); if (!code || !name) { rejected++; return; } const values = { code, name, category: row[index(["category"])] || "Other", model: row[index(["model"])] || "", serial: row[index(["serialnumber", "serial"])] || "", status: row[index(["status"])] || "Available", location: row[index(["location"])] || db.locations[0], owner: row[index(["currentholder", "owner"])] || "", department: row[index(["department"])] || "", condition: row[index(["condition"])] || "Good", notes: row[index(["notes"])] || "", updated: new Date().toISOString().slice(0, 10) }; const existing = db.assets.find((asset) => asset.code === code); if (existing) { Object.assign(existing, values); updated++; } else { db.assets.push({ id: crypto.randomUUID(), ...values }); added++; } }); saveDb(); render(); toast(`Import complete: ${added} added, ${updated} updated, ${rejected} rejected`); event.target.value = ""; }; reader.readAsText(file); }
$("#modalClose").addEventListener("click", closeModal); $("#modalBackdrop").addEventListener("click", (event) => { if (event.target === $("#modalBackdrop")) closeModal(); }); $("#backupButton").addEventListener("click", () => { download(new Blob([JSON.stringify(db, null, 2)], { type: "application/json" }), `asset-index-backup-${new Date().toISOString().slice(0, 10)}.json`); toast("Local backup downloaded"); }); document.querySelectorAll(".nav-item").forEach((button) => button.addEventListener("click", () => setView(button.dataset.view))); $("#todayLabel").textContent = new Intl.DateTimeFormat("en", { weekday: "long", month: "long", day: "numeric" }).format(new Date()).toUpperCase(); render();
